/*
 * ultrasonic_sensor.c
 *
 *  Created on: Oct 12, 2022
 *      Author: georg
 */

#include "ultrasonic_sensor.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h> /* For the delay functions */

/*******************************************************************************
 *                           Static Variables                                  *
 *******************************************************************************/

static volatile uint8  g_edgeCount   = 0;
static volatile uint16 g_timeHigh    = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description:
 *1. Initialize the ICU driver.
 *2. Setup the ICU call back function.
 *3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void){
	Icu_ConfigType ICU_Configurations = {F_CPU_8,RISING};
	Icu_init( &ICU_Configurations);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_SENSOR_TRIG_PORT_ID,ULTRASONIC_SENSOR_TRIG_PIN_ID,PIN_OUTPUT);
}

/*
 * Description: Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(ULTRASONIC_SENSOR_TRIG_PORT_ID,ULTRASONIC_SENSOR_TRIG_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_SENSOR_TRIG_PORT_ID,ULTRASONIC_SENSOR_TRIG_PIN_ID,LOGIC_LOW);
}

/*
 * Description:
 *1.Send the trigger pulse by using Ultrasonic_Trigger function.
 *2.Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	return ((float)(g_timeHigh/57.8));

}

/*
 * Description:
 * 1. This is the call back function called by the ICU driver.
 * 2. Used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();

		/*Clear Timer counter register*/
		Icu_clearTimerValue();

		/*Detect Rising edge*/
		Icu_setEdgeDetectionType(RISING);

		g_edgeCount = 0;
	}
}
