/*
 * ultrasonic_sensor.h
 *
 *  Created on: Oct 12, 2022
 *      Author: georg
 */

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ULTRASONIC_SENSOR_TRIG_PORT_ID		PORTB_ID
#define ULTRASONIC_SENSOR_TRIG_PIN_ID		PIN5_ID

#define ULTRASONIC_SENSOR_ECHO_PORT_ID		PORTD_ID
#define ULTRASONIC_SENSOR_ECHO_PIN_ID		PIN6_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description:
 *1. Initialize the ICU driver.
 *2. Setup the ICU call back function.
 *3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description: Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * Description:
 *1.Send the trigger pulse by using Ultrasonic_Trigger function.
 *2.Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description:
 * 1. This is the call back function called by the ICU driver.
 * 2. Used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_SENSOR_H_ */
